### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by luckyluk92**
This PR changes a lot. When I found your plugin it did and looked almost exactly like I needed it. Almost because I needed few more things. 

* I divided the whole gallery into smaller components.
* I rewrite the stylesheet to BEM and divided into smaller chunks.
* I made possible to override components, but I needed to add more complexity with require :disappointed: However this worked very well in my use-case (I've updated the README).
* I removed the logic taking care of ghost click and decided to go with [react-tab-event-plugin](https://github.com/zilverline/react-tap-event-plugin).
* I changed a file extension from `.react.jsx` to `.es6.jsx`.

I'm aware that you may not like my changes but I'm looking forward to get some comments

### CODE REVIEW

**Comment by xiaolin** [comment]
@luckyluk92  I really appreciate your pull request, and the time you took to refactor. To be completely  honest, I do like some stuff, but this changes too much, and it seems like you focused more on your personal style preferences than adding a critical feature.

**Feedback**
_"I divided the whole gallery into smaller components."_ - That was great, but you divided it into too many components. We want to create reusable components, my rule of thumb when creating new components is if I can see it being reused in the future, or if it has a complicated ui state it needs to manage on its own. Components like `Bullet`, `BulletsContainer`, `Image`, `Index`, `LeftNav`, `RightNav`, etc... these are all very specific in their functions, and will probably never be reused or grow to have more complicated functions. Id much prefer going with [stateless functions](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions) for these components, and keeping them all in the same file.

_"I rewrite the stylesheet to BEM and divided into smaller chunks."_ - I'm not against this convention, It was new to me, and I did some brief reading on it, I'm willing to try it out. What I don't like is the whole stylesheets directory, especially since I only see the styles as an out of the box style. Most people re-style the css based on their own needs. Eventually, I want to try out [JSS](https://github.com/jsstyles/jss) for single components like this where people can install and expect it to work without css installation overhead.

"I made possible to override components,..." - This is an awesome feature, but I don't think many people would actually use this. This also breaks backward compatibility. I'm curious what your use case was that you would need this type of feature? I think we can solve your use case without this feature.

_"I removed the logic taking care of ghost click and decided to go with react-tab-event-plugin"_ - I wanna have as little to zero dependencies for a small component like this. I plan to remove `react-swipeable` in the near future to create a better swipeable user experience. In any case, If there is a really good reason for using `react-tab-event-plugin` then thats okay, but Its not obvious to me.

_"I changed a file extension from `.react.jsx` to `.es6.jsx`"_ - I prefer just `filename.jsx`, its simpler and somewhat more future proof.

**Other comments:**
I noticed you used `React.createClass` instead of the es6 syntax, if its because of `PureRenderMixin`? es6 syntax also supports [PureRenderMixin](https://facebook.github.io/react/docs/pure-render-mixin.html).

**Conclusion:**
The goal of this project is simplicity, and ease of use. The current project has only 440 lines of code and I don't want to overcomplicate it. Two files (jsx, and scss) is enough for now.

Please open small incremental pull requests, and if its a major feature you should consider opening up an issue for collaboration (e.g. override components), most of the time there is a simpler solution. This pull request changes too much, has bugs (wouldn't even work until I removed `../utils` from `ImageGallery`), and its not backwards compatible. You should definitely consider working in iterations for things like this, otherwise you end up opening a `+1,285 −676` PR  :fearful: :fearful:

**Comment by luckyluk92** [comment]
@xiaolin, thank you for your feedback :) I'm aware that this changes too much and because of that it won't be merged. I did it more for ideas confrontation.

**Personal style**
Yeah, that basically true, the only "features" I added are:

* overriding components
* optional looping
* optional description

That's it. But for my usecase they were crucial. I needed custom navigation arrows within thumbnails level, custom description box and no looping.

**Too many components**
I think this is a matter of style. I like extracting components because for me it makes the parent component clearer. It doesn't have to take care of css classes which are added based on props or an event  which parent deals with, can get an actual element from collection rather than an event object. I think that components  which are specific in their nature aren't bad because in some cases you want wrap sometimes a general component to make the code more expressive.

**File extension**
The `.jsx` is the best but I uses `.es6.jsx` or `.js.jsx` because I write code both in es6 and pure js. Because of that, it is easier for me to manage with snippets :smiley: 

**react-tab-event-plugin**
I used it because I thought it makes the code cleaner and in some time in future, React itself will deal with ghost clicks. But I understand your concern about dependencies.

**React.createClass**
I'm aware that `PureRenderMixin` supports es6 syntax. I use `createClass` because of personal taste. I still work on some code which depends on mixins and I just use `createClass` everywhere :laughing: 

**Other comments**
I understand that this plugin is all about simplicity of use, that's why I wasn't event sure I make a PR. Sorry for the bug, I had deleted the `utils` file just before creating the PR and I forgot to delete the `import` :confused: 

Sorry for possible mistakes with my English :smiley:

**Comment by xiaolin** [comment]
> optional description

Did you need custom HTML markup for the descriptions? If so you can always add your own markup and style it so that it fits in the gallery. e.g.

```javascript
handleSlide (index) {
   this.setState({description: getMydescription(index)})
}

render() {
  <div className='my-image-gallery'>
    <ImageGallery onSlide={this.handleSlide.bind(this)}/>
    <div className='slide-description'>
      {this.state.description}
    </div>
  </div>
}
```
```css
.my-image-gallery {
  position: relative;

  .slide-description {
    position: absolute;
    right: 0;
    bottom: <some appropriate bottom offset>;
  }
}
```
> custom navigation arrows within thumbnails

This would be a good feature to add. Turned on via props.

> optional looping

Also a very good feature to add. Turned on via props.

Most of the component overrides that you wanted, are good feature that the library needs. This is why most people won't use the overriding component feature, because the component they write will be dependent on the ImageGallery to always work with it, and they have to maintain it if the library updates. For stuff like optional looping, and thumbnail navigation, it should just be included in the library.

**Comment by luckyluk92** [comment]
The example with description won't work when you pass html through description prop. You'd need [this](https://facebook.github.io/react/tips/dangerously-set-inner-html.html), but yeah you're right. I see now, that I've gone a little bit too far :smile:

**Pull request closed without merging**
