### PR TITLE
fix issue #288

### PR DESCRIPTION
**Pull request by frayeralex**
- add private property _isMounted to avoid calling  setState() after component unmounted

### CODE REVIEW

**Comment by hchoriq** [comment]
I'm going to try this fix tonight; I'm running into this problem in my app.

**Comment by madeinfree** [comment]
Hi @xiaolin, this is code sandbox link to reproduce the problem

https://codesandbox.io/s/64vk0m8lnr (in the sample, quick to click button two times)

because use lodash debounce but didn't clear when component unmount cause this problem ~

https://github.com/xiaolin/react-image-gallery/blob/master/src/ImageGallery.jsx#L423
```
 _createResizeObserver = debounce((entries) => {
   entries.forEach(() => {
     this._handleResize();
   });
 }, 300);
```
I think maybe change into this
```
 _createResizeObserver = debounce((entries) => {
   if(!entries) return; // when clear debounce then entries is null
   entries.forEach(() => {
     this._handleResize();
   });
 }, 300);
```
and `componentWillUnmount`
```
this._createResizeObserver() // call the same debounce reference and lodash allow to clear the debounce.
```

**Comment by xiaolin** [comment]
@madeinfree Thank you for the detailed explanation! Would you like to open a PR? If not I can open one later this week now that I know how to reproduce it.

**Comment by madeinfree** [comment]
OK ! I will be open a new PR.

**Comment by xiaolin** [comment]
closing in favor of #328

**Pull request closed without merging**
