### PR TITLE
Add debounce to window resize event

### PR DESCRIPTION
**Pull request by DaryaVeretennikova**
#158

### CODE REVIEW

**Comment by xiaolin** [comment]
@DaryaVeretennikova thanks for the PR, can you squash this into one commit? I'll take a look as soon as I get a chance. Thanks!

**Comment by DaryaVeretennikova** [comment]
@xiaolin you can choose option "squash and merge" when you'll accept the PR. [More about it](https://github.com/blog/2141-squash-your-commits)

Will that be okay?)

**Comment by xiaolin** [comment]
@DaryaVeretennikova totally forgot about that, haha sure I could do that!

**Comment by DaryaVeretennikova** [comment]
Cool! Thank you for your work :)

**Pull request merged**
