### PR TITLE
Check _imageGallery Not Null And Bind Context To _handleIm…

### PR DESCRIPTION
**Pull request by jwdotjs**
…ageError

Side Note: These changes are untested, I would have pushed a build up to QA, but currently the build folder is in .gitignore and there is no prepublish command, so I can't test a remote fork without publishing to NPM (that I know of). It might be helpful to add a prepublish or a build script to fix that. 

### _imageGallery is undefined on Mobile Safari sometimes 

screen shot 2016-04-12 at 7 30 23 am

screen shot 2016-04-12 at 7 30 29 am

### `this` is undefined on _handleImageError

screen shot 2016-04-12 at 7 29 54 am

screen shot 2016-04-12 at 7 30 10 am

### CODE REVIEW

**Comment by xiaolin** [comment]
Will take a look sometime this week. Thanks for the PR.

**Comment by xiaolin** [comment]
I have applied the fixes into the next major release (sometime this week), will keep you posted.

**Comment by jwdotjs** [comment]
👍  Thank you!

**Comment by xiaolin** [comment]
updated in release v0.6.0

**Pull request closed without merging**
