### PR TITLE
Thumbs scroll bug

### PR DESCRIPTION
**Pull request by delacalera**
Solved "Strange initial animation when startIndex is set" issue, added an answer in the Issue post to explain the solution and TODO comments in the code.

### CODE REVIEW

**Comment by xiaolin** [comment]
Merged.

**Comment by delacalera** [comment]
Hi Xiao,There was another small change to implement. As I didn't get any response I created my own repository with the changes I needed.You can find it in the following URL:https://github.com/delacalera/react-image-galleryI've added a TODO comment so you can easily search it instead of compare versions.Please feel free to take a look to the differences in the code and implement the requested changes if you agree.Thank you very muchEl 14 de septiembre de 2017 a las 5:43 Xiao Lin <notifications@github.com> escribió:Merged.--You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub:https://github.com/xiaolin/react-image-gallery/pull/209#issuecomment-329361397

**Comment by xiaolin** [comment]
@delacalera the changes you adjusted were merged. All I did was remove the todo comments.
take a look at https://github.com/xiaolin/react-image-gallery/commit/e475c2dd1c5505d22f9f8bc7a7f654cd00cf29ce

**Comment by delacalera** [comment]
Thanks

**Pull request closed without merging**
