### PR TITLE
Extra params for custom Slide component to know if active or not

### PR DESCRIPTION
**Pull request by kftsehk**
To allow some feature like stop and rewinding a video once the slide goes out of scope.
Currently there seem no interface for a cutsom `renderItem` function to know if it is active or not.

Therefore this PR added such parameters, since parameters are added only, it is fully backward compatible.

Still this PR is prototypical, still have to test, adding docs and type for the new interface.

### CODE REVIEW

**Comment by xiaolin** [comment]
You can use `getCurrentIndex` to check the active index.

**Comment by kftsehk** [comment]
Hi, thanks for reply, I did not get how getCurrentIndex() can be used to make changes on rendered item, `onSlide` might be used, but that requires the parent of `ImageGallery` to keep track of everything and how to use each item.

I believe having them available in the renderItem function makes the implementation much simpler and self-contained, like
```
useEffect(()=>{
  if(isActive){
    // slide is showing
  } else {
    // slide is running out of view
  }
}, [isActive])
```
in the rendered item itself.

**Comment by xiaolin** [comment]
So what you can do is something like this (untested 😛)

```js
const items = [
  {
    original: 'image1.jpg',
    // can also use findIndex if you have ids as a property in items
    index: 0,
  },
  {
    original: 'image2.jpg',
    // can also use findIndex if you have ids as a property in items
    index: 1,
  }
]

renderItem(item) {
  const isActive = item.index === this.imageGallery.getCurrentIndex();
  return (
    <MyCustomItem isActive={isActive} />
  )
}

render() {
  <ImageGallery ref={this.imageGallery} renderItem={renderItem}
}
```

**Comment by kftsehk** [comment]
I see, to clarify a bit, we met a scenario, we have a list of items and this is what we want to achieve, like

```javascript
const item = [
  { type: "Image"}, 
  { type: "Video", renderItem={VideoPlayer}}, 
  { type: "Audio", renderItem={AudioPlayer}}, 
  { type: "Video", renderItem={YoutubeEmbedder}}
]
```
it is quite natural to expect each one uses the `item.renderItem` function, and __it does work as said in readme__.

Later, we find that player need to stop themselves from playing when is not current, since otherwise the activated player continues to play, emitting audio, and player on the next slide might start playing another stream of audio too.
So we look for how to let _each `renderItem` component_ know if they are out of scope, and have them stop playing.

I just tested your method above, it works for one custom renderer, the reason is here that we will use `item.renderItem`  whenever available, skipping `props.renderItem`.

https://github.com/xiaolin/react-image-gallery/blob/445c8ddc734892c5c8b1989562949f794f8ba1f2/src/ImageGallery.js#L500


### So here are the 2 solutions that may work, without library code change

Both assumes any props in item can be passed into `item.renderItem`, which seem the case of the library, that extra props in item won't be deleted.

__Workaround 1: Put `ref` to `ImageGallery` into each item. (untested)__

```javascript
// not tested
const ref = useRef() // will assign ref
const item = useMemo(()=>[{ type: "Image"}, {  type: "Video", renderItem={VideoPlayer}, ref={ref}}, {type: "Audio", renderItem={AudioPlayer}, ref={ref}}, {type: "Video", renderItem={YoutubeEmbedder}, ref={ref}}], [ref])
```
Doesn't seem a good idea to have a circular ref that a parent to have list of child and child keep a ref to the parent too.

__Workaround 2: use `props.renderItem`, and name `item.renderItem` something else. (tested working)__

```javascript
const ref = useRef() // will assign ref
const items = useMemo(()=>[{ type: "Image"}, {  type: "Video", renderFunction={VideoPlayer}}, {type: "Audio", renderFunction={AudioPlayer}}, {type: "Video", renderFunction={YoutubeEmbedder}}], [ref])

return (<ImageGallery
  ref={ref}
  items={items}
  renderItem={(item) => {
    const isCurrent =
      item.index === imageGallary.current?.getCurrentIndex();
    // here we need the library's default renderItem function in case one is not supplied
    return (item.renderFunction ?? imageGallary.current?.renderItem)?.({
      ...item,
      isActive: isCurrent,
    });
  }}
```

This is probably more usable than the previous one, but to handle the case where renderFunction is not specified, like `type: "Image"` in above example where the default serves exactly the purpose, our custom `renderItem` has to fallback to the library's `this.renderItem`, and thus have a reference to the internal working of the library.

### The proposal in the PR

Is a third option that the library will add `index`, `currentIndex`, and `isCurrent` to props of `renderItem`, making the original code works without any workaround.

```javascript
const VideoPlayer = ({ isCurrent, ...item })=>{
  useEffect(()=> {
    if(isCurrent){
      // start playing
    } else {
      // stop playing
    }, [isCurrent]);

  return // ...
}

const item = [{ type: "Image"}, {  type: "Video", renderItem={VideoPlayer}}, {type: "Audio", renderItem={AudioPlayer}}, {type: "Video", renderItem={YoutubeEmbedder}}]
```

**Comment by xiaolin** [comment]
Yes, workaround #2 would work, but you can set `renderItem` to null and the default will be used.

e.g.
```js
const item = [
  { type: "Image"}, 
  { type: "Video", renderItem={VideoPlayer}}, 
  { type: "Audio", renderItem={AudioPlayer}}, 
  { type: "Video", renderItem={YoutubeEmbedder}}
]

renderItem(item) {
  const isActive = item.index === this.imageGallery.getCurrentIndex();
  if (item.type === 'image') return null; // default back to gallery renderItem
  return (
    <MyCustomItem isActive={isActive} />
  )
}
```

The reason I'm hesitant about adding the extra params to `renderItem` is that it will be called internally every time and will be unused.

**Comment by kftsehk** [comment]
I think workaround (2) doesn't work that way, in your example, the `item.renderItem` takes priority so there is no chance to get currentIndex either. 
Btw if returning null it will render nothing, not falling back to default.

The actual invocation priority of workaround (2) is actually `ImageGallery.props.` -> `item.renderFunction` (_not_ `renderItem`) -> (fallback) `ImageGallery.renderItem`

If calculating isActive is your concern, how about adding ` currentIndex` and `index` which are not calculated quantity, 
Anyway for performance I believe the `renderItem` function should be memoized, and if someone is not interested in the `currentIndex` and `index`, they won't be listed in memoization, so effectively nothing is recalculated.

**Comment by xiaolin** [comment]
My bad, updated the piece to reflect using `renderItem` as a prop not `item.renderItem`

**Comment by xiaolin** [comment]
Let me know if this solves your issue.

**Comment by kftsehk** [comment]
Hi

In term of does it works, yes.

In term of code maintainability, no imo. The point is, the whole workaround is essentially copying the library `props.renderItem` implementation, in order to implement another per item `item.renderFunction` which is an exact replacement to the library's `item.renderItem` plus 2 extra parameters, just shows that the library can be implemented in a way that offers the feature for free.

**Comment by xiaolin** [comment]
Another suggestion that may be simpler and more maintainable is possibly using prop `onSlide(currentIndex)`. You can stop and rewind all videos that are not in the `currentIndex` after `onSlide` is called.

```
onSlide(currentIndex) {
  // rewind all videos !== currentIndex
}
```

**Pull request closed without merging**
