### PR TITLE
Fix-bug-for-remove-event: the event handler is not the same in attach…

### PR DESCRIPTION
**Pull request by bibobibo**
… and remove

### CODE REVIEW

**Comment by xiaolin** [comment]
@bibobibo nice catch.

**Comment by pleary** [comment]
We just started using this library (very cool!) and we're also hitting the problem fixed by this pull request. Do you have plans to release a new version to NPM to include this fix? Thanks!

**Comment by xiaolin** [comment]
I will release a minor version tonight. Will update you soon!

**Comment by xiaolin** [comment]
@bibobibo @pleary released in v0.5.13

**Comment by pleary** [comment]
Works great - thanks for the quick turnaround

**Pull request merged**
