### PR TITLE
chore(react): update react-swipeable dependency and moved to prop-types

### PR DESCRIPTION
**Pull request by devCrossNet**
related to #178

### CODE REVIEW

**Comment by JordyVialoux** [comment]
I took your code and threw it into my own local version of the package. I still get the warning regarding proptypes is depreciated. Was this code intended to resolve this?

**Comment by xiaolin** [comment]
Thanks for the PR. I will look at this pr this weekend, and fix up any dependency issues with react 15.5

**Comment by devCrossNet** [comment]
I tested it locally inside the project (not linked it to any application with `npm link`) and it worked. @JordyVialoux did you also update the react-swipeable dependency?

**Comment by JordyVialoux** [comment]
@devCrossNet In short I copied the whole files you edited and replaced within the package. I'm using "react": "^15.4.1"

**Comment by devCrossNet** [comment]
@JordyVialoux I don't think that works because you have to update the react-swipeable dependency.

you can try to clone my fork and npm link it after you built the project.

**Pull request merged**
