### PR TITLE
Thumbnails navigation.

### PR DESCRIPTION
**Pull request by m00n-als**

### CODE REVIEW

**Comment by xiaolin** [comment]
Thanks for the PR, will take a look soon!

**Comment by omdriven** [comment]
Hey @xiaolin, how about merging this feature? Looking forward to involve this gallery into my project too, would be cool to use these thumbnails there

**Comment by xiaolin** [comment]
I'll take a look this weekend, I notice @m00n-als adding changes, so thought Id give him some more time 👍

**Comment by xiaolin** [comment]
@m00n-als Thanks for opening a PR, and making the code easy to read and follow. Right now the thumbnail swiping doesn't feel natural. I'm aiming to make the gallery similar to how iOS photos handle their thumbnail swiping. If you wanna take a stab at that it would be great, if not I'll try to implement it soon.

**Comment by m00n-als** [comment]
@xiaolin I'll try to make thumbnail swiping more natural. Maybe this weekend. If there are any difficulties, I'll write.

**Comment by mjvalade** [comment]
Hi @xiaolin any progress on this? Adding some nav arrows and swiping for the thumbnails would be a great addition for our users. Thanks!

**Comment by xiaolin** [comment]
@mjvalade I have not had time to finish up this feature. I was working on a branch with this feature, but it got a bit complicated. I'll take another look when I get some time.

**Comment by xiaolin** [comment]
Cleaning up some PRs, and notice this has been hanging around. Closing this as its not the ideal UX for the gallery. Feel free to open a new pr with updates when available.

**Pull request closed without merging**
