### PR TITLE
adding true lazy loading for slides

### PR DESCRIPTION
**Pull request by tadjohnston**
This looks like it should be enough to fix the issue described at https://github.com/xiaolin/react-image-gallery/issues/278

### CODE REVIEW

**Comment by xiaolin** [comment]
@tadjohnston Placeholder was added because of #137 Does this also solve the jumping issue?

**Comment by xiaolin** [comment]
@tadjohnston Lazy loading was intended on lazy loading images, not the entire slide. The extra dom nodes are a bit unnecessary and I'm up for a better solution, but they are in place right now for a specific reason. You mentioned in #278 "The problem is magnified". Were you able to see a decrease in performance because of the empty nodes?

**Comment by tadjohnston** [comment]
@xiaolin yes, because we have 12 carousels on the page each with approximately 30 photos.  That means, even lazy loaded, we end up decreasing overall node total by close to 700 nodes. That's pretty substantial.

**Comment by xiaolin** [comment]
Closing this for now as its not backwards compatible with #137.

**Pull request closed without merging**
